# one-dark inspired
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

dim_foreground    = '#828997'
bright_foreground = '#e5c07b'

[colors.cursor]
text   = '#282c34'
cursor = '#528bff'

[colors.normal]
black   = '#282c34'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#e5c07b'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#dcdfe4'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#e5c07b'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[colors.dim]
black   = '#1c1f24'
red     = '#b24c50'
green   = '#7fa97f'
yellow  = '#c8a65e'
blue    = '#3e80c5'
magenta = '#9b59b6'
cyan    = '#3ab0b3'
white   = '#90969c'

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 12.5

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetbrainsMono"
style = "Regular"

[scrolling]
history = 3000

[window]
opacity = 0.95

[window.padding]
x = 6
y = 6

[window.position]
x = 2
y = 2

